awk '{print $1}' demcmc_starparm.* > tempELC.M1solar
awk '{print $2}' demcmc_starparm.* > tempELC.M2solar
awk '{print $3}' demcmc_starparm.* > tempELC.R1solar
awk '{print $4}' demcmc_starparm.* > tempELC.R2solar
awk '{print $5}' demcmc_starparm.* > tempELC.log_g1
awk '{print $6}' demcmc_starparm.* > tempELC.log_g2
awk '{print $7}' demcmc_starparm.* > tempELC.den1
awk '{print $8}' demcmc_starparm.* > tempELC.den2
awk '{print $9}' demcmc_starparm.* > tempELC.fill1
awk '{print $10}' demcmc_starparm.* > tempELC.fill2
awk '{print $11}' demcmc_starparm.* > tempELC.K1
awk '{print $12}' demcmc_starparm.* > tempELC.K2
awk '{print $13}' demcmc_starparm.* > tempELC.Vrot1
awk '{print $14}' demcmc_starparm.* > tempELC.Vrot2
awk '{print $15}' demcmc_starparm.* > tempELC.Vrot1_omega1
awk '{print $16}' demcmc_starparm.* > tempELC.Vrot2_omega2
awk '{print $17}' demcmc_starparm.* > tempELC.tspot_1_1
awk '{print $18}' demcmc_starparm.* > tempELC.tspot_2_1
awk '{print $19}' demcmc_starparm.* > tempELC.tspot_1_2
awk '{print $20}' demcmc_starparm.* > tempELC.tspot_2_2
awk '{print $21}' demcmc_starparm.* > tempELC.tspot_1_disk
awk '{print $22}' demcmc_starparm.* > tempELC.tspot_2_disk
awk '{print $23}' demcmc_starparm.* > tempELC.diskrad
awk '{print $24}' demcmc_starparm.* > tempELC.diskthick
awk '{print $25}' demcmc_starparm.* > tempELC.X_duras
awk '{print $26}' demcmc_starparm.* > tempELC.impact1
awk '{print $27}' demcmc_starparm.* > tempELC.tran_duras
awk '{print $28}' demcmc_starparm.* > tempELC.tran_depth
awk '{print $29}' demcmc_starparm.* > tempELC.tran_duras_alt
awk '{print $30}' demcmc_starparm.* > tempELC.M2earth
awk '{print $31}' demcmc_starparm.* > tempELC.R2earth
awk '{print $32}' demcmc_starparm.* > tempELC.period2days
awk '{print $33}' demcmc_starparm.* > tempELC.a2AU
awk '{print $34}' demcmc_starparm.* > tempELC.ecc2
awk '{print $35}' demcmc_starparm.* > tempELC.argper2deg
awk '{print $36}' demcmc_starparm.* > tempELC.incl2deg
awk '{print $37}' demcmc_starparm.* > tempELC.Omega2deg
awk '{print $38}' demcmc_starparm.* > tempELC.Tconj2
awk '{print $39}' demcmc_starparm.* > tempELC.Tperi2
awk '{print $40}' demcmc_starparm.* > tempELC.mutual2deg
